newsroom/urls.py
from django.urls import path
from .views import home, categories, single_news, contact, quick_links_view, register, login_view, logout_view

app_name = 'newsroom'
urlpatterns = [
    path('', home, name="home"),
    path('categories/', categories, name="categories" ),
    path('single_news/', single_news, name="single_news"),
    path('contact/', contact, name='contact'),
    path('quick_links/', quick_links_view, name='quick_links'),
    path('login/', login_view, name= 'login'),
    path('register/', register, name='register'),
    path('logout/', logout_view, name='logout')

]

second_page/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = ([
    path('admin/', admin.site.urls),
    path('', include("newsroom.urls"))
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>NEWSROOM - Free Bootstrap Magazine Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="{% static 'base_site/img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'base_site/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'base_site/css/style.css' %}" rel="stylesheet">
</head>

<body>
    <!-- Topbar Start -->
    <div class="container-fluid">
        <div class="row align-items-center bg-light px-lg-5">
            <div class="col-12 col-md-8">
                <div class="d-flex justify-content-between">
                    <div class="bg-primary text-white text-center py-2" style="width: 100px;">Tranding</div>
                    <div class="owl-carousel owl-carousel-1 tranding-carousel position-relative d-inline-flex align-items-center ml-3" style="width: calc(100% - 100px); padding-left: 90px;">
                        <div class="text-truncate"><a class="text-secondary" href="{{information.link_currency}}">{{information.currency}}</a></div>
                        <div class="text-truncate"><a class="text-secondary" href="{{information.link_weather}}">{{information.weather}}</a></div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 text-right d-none d-md-block">
                {{information.date_time}}
            </div>
        </div>
        <div class="row align-items-center py-2 px-lg-5">
            <div class="col-lg-4">
                <a href="{% url 'newsroom:home' %}" class="navbar-brand d-none d-lg-block">
                    <h1 class="m-0 display-5 text-uppercase"><span class="text-primary">News</span>Room</h1>
                </a>
            </div>
            <div class="col-lg-8 text-center text-lg-right">
                <img class="img-fluid" src="{% static 'base_site/img/ads-700x70.jpg' %}" alt="">
            </div>
        </div>
    </div>
    <!-- Topbar End -->


    <!-- Navbar Start -->
    <div class="container-fluid p-0 mb-3">
        <nav class="navbar navbar-expand-lg bg-light navbar-light py-2 py-lg-0 px-lg-5">
            <a href="" class="navbar-brand d-block d-lg-none">
                <h1 class="m-0 display-5 text-uppercase"><span class="text-primary">News</span>Room</h1>
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between px-0 px-lg-3" id="navbarCollapse">
                <div class="navbar-nav mr-auto py-0">
                    <a href="{% url 'newsroom:home' %}" class="nav-item nav-link {% if request.path == '/'%} active {% endif %}">Home</a>
                    <a href="{% url 'newsroom:categories' %}" class="nav-item nav-link {% if request.path == '/categories/'%} active {% endif %}">Categories</a>
                    <a href="{% url 'newsroom:single_news' %}" class="nav-item nav-link {% if request.path == '/single_news/'%} active {% endif %}">Single News</a>
                    <a href="{% url 'newsroom:quick_links' %}" class="nav-item nav-link {% if request.path == '/quick_links/'%} active {% endif %}">About</a>
                    <a href="{% url 'newsroom:contact' %}" class="nav-item nav-link {% if request.path == '/contact/'%} active {% endif %}">Contact</a>
                    {% if user.is_authenticated %}
                    <a href="{% url 'newsroom:logout' %}" class="nav-item nav-link {% if request.path == '/logout/'%} active {% endif %}"><b>Logout</b></a>
                    {% else %}
                    <a href="{% url 'newsroom:register' %}" class="nav-item nav-link {% if request.path == '/register/'%} active {% endif %}"><b>Register</b></a>
                    <a href="{% url 'newsroom:login' %}" class="nav-item nav-link {% if request.path == '/login/'%} active {% endif %}"><b>Login</b></a>
                    {% endif %}
                </div>
                <div class="input-group ml-auto" style="width: 100%; max-width: 300px;">
                    <input type="text" class="form-control" placeholder="Keyword">
                    <div class="input-group-append">
                        <button class="input-group-text text-secondary"><i
                                class="fa fa-search"></i></button>
                    </div>
                </div>
            </div>
        </nav>
    </div>
    <!-- Navbar End -->

{% block content %}{% endblock %}

<!-- Footer Start -->
<div class="container-fluid bg-light pt-5 px-sm-3 px-md-5">
    <div class="row">
        <div class="col-lg-3 col-md-6 mb-5">
            <a href="index.html" class="navbar-brand">
                <h1 class="mb-2 mt-n2 display-5 text-uppercase"><span class="text-primary">News</span>Room</h1>
            </a>
            <p>Volup amet magna clita tempor. Tempor sea eos vero ipsum. Lorem lorem sit sed elitr sed kasd et</p>
            <div class="d-flex justify-content-start mt-4">
            {% for platform in platforms %}
                <a class="btn btn-outline-secondary text-center mr-2 px-0" style="width: 38px; height: 38px;" href="{{platform.platform_link}}"><i class="{{platform.icons}}"></i></a>
            {% endfor %}
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mb-5">
            <h4 class="font-weight-bold mb-4">Categories</h4>
            <div class="d-flex flex-wrap m-n1">
            {% for category in all_categories %}
                <a href="{{category.link}}" class="btn btn-sm btn-outline-secondary m-1">{{category.name}}</a>
            {% endfor %}
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mb-5">
            <h4 class="font-weight-bold mb-4">Tags</h4>
            <div class="d-flex flex-wrap m-n1">
            {% for tag in tags %}
                <a href="{{tag.link}}" class="btn btn-sm btn-outline-secondary m-1">{{tag.name}}</a>
            {% endfor %}
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mb-5">
            <h4 class="font-weight-bold mb-4">Quick Links</h4>
            <div class="d-flex flex-column justify-content-start">
            {% for link in links %}
                <a class="text-secondary mb-2" href="{{link.link}}"><i class="fa fa-angle-right text-dark mr-2"></i>{{link.name}}</a>
            {% endfor %}

            </div>
        </div>
    </div>
</div>
<div class="container-fluid py-4 px-sm-3 px-md-5">
    <p class="m-0 text-center">
        &copy; <a class="font-weight-bold" href="#">Your Site Name</a>. All Rights Reserved.

        <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
        Designed by <a class="font-weight-bold" href="https://htmlcodex.com">HTML Codex</a>
    </p>
</div>
<!-- Footer End -->


<!-- Back to Top -->
<a href="#" class="btn btn-dark back-to-top"><i class="fa fa-angle-up"></i></a>


<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'base_site/lib/easing/easing.min.js' %}"></script>
<script src="{% static 'base_site/lib/owlcarousel/owl.carousel.min.js' %}"></script>

<!-- Contact Javascript File -->
<script src="{% static 'base_site/mail/jqBootstrapValidation.min.js' %}"></script>
<script src="{% static 'base_site/mail/contact.js' %}"></script>

<!-- Template Javascript -->
<script src="{% static 'base_site/js/main.js' %}"></script>

templates/categories.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Categories{% endblock %}

{% block content %}
    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="container">
            <nav class="breadcrumb bg-transparent m-0 p-0">
                <a class="breadcrumb-item" href="{% url 'newsroom:home' %}">Home</a>
                <a class="breadcrumb-item" href="{% url 'newsroom:categories' %}">Category</a>
                <span class="breadcrumb-item active">Technology</span>
            </nav>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- News With Sidebar Start -->
    <div class="container-fluid py-3">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="row">
                        <div class="col-12">
                            <div class="d-flex align-items-center justify-content-between bg-light py-2 px-4 mb-3">
                                <h3 class="m-0">Technology</h3>
                                <a class="text-secondary font-weight-medium text-decoration-none" href="">View All</a>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            {% for news in featured_left %}
                                <div class="position-relative mb-3">
                                    <img class="img-fluid w-100" src="{{news.image.url}}" style="object-fit: cover;">
                                    <div class="overlay position-relative bg-light">
                                        <div class="mb-2" style="font-size: 14px;">
                                            <a href="">{{news.category}}</a>
                                            <span class="px-1">/</span>
                                            <span>{{news.published_at}}</span>
                                        </div>
                                        <a class="h4" href="{{news.link}}">{{news.title}}</a>
                                        <p class="m-0">{{news.content}}</p>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="col-lg-6">
                            {% for news in featured_right %}
                                <div class="position-relative mb-3">
                                    <img class="img-fluid w-100" src="{{news.image.url}}" style="object-fit: cover;">
                                    <div class="overlay position-relative bg-light">
                                        <div class="mb-2" style="font-size: 14px;">
                                            <a href="">{{news.category}}</a>
                                            <span class="px-1">/</span>
                                            <span>{{news.published_at}}</span>
                                        </div>
                                        <a class="h4" href="{{news.link}}">{{news.title}}</a>
                                        <p class="m-0">{{news.content}}</p>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="mb-3">
                        <a href=""><img class="img-fluid w-100" src="{% static 'base_site/img/ads-700x70.jpg' %}" alt=""></a>
                    </div>

                    <div class="row">
                        <div class="col-lg-6">
                        {% for news in remaining_left %}
                            <div class="d-flex mb-3">
                                <img src="{{news.image.url}}" style="width: 100px; height: 100px; object-fit: cover;">
                                <div class="w-100 d-flex flex-column justify-content-center bg-light px-3" style="height: 100px;">
                                    <div class="mb-1" style="font-size: 13px;">
                                        <a href="">{{news.category}}</a>
                                        <span class="px-1">/</span>
                                        <span>{{news.published_at}}</span>
                                    </div>
                                    <a class="h6 m-0" href="{{news.link}}">{{news.title}}</a>
                                </div>
                            </div>
                        {% endfor %}
                        </div>
                        <div class="col-lg-6">
                        {% for news in remaining_right %}
                            <div class="d-flex mb-3">
                                <img src="{{news.image.url}}" style="width: 100px; height: 100px; object-fit: cover;">
                                <div class="w-100 d-flex flex-column justify-content-center bg-light px-3" style="height: 100px;">
                                    <div class="mb-1" style="font-size: 13px;">
                                        <a href="">{{news.category}}</a>
                                        <span class="px-1">/</span>
                                        <span>{{news.published_at}}</span>
                                    </div>
                                    <a class="h6 m-0" href="{{news.link}}">{{news.title}}</a>
                                </div>
                            </div>
                        {% endfor %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <nav aria-label="Page navigation">
                              <ul class="pagination justify-content-center">
                                <li class="page-item disabled">
                                  <a class="page-link" href="#" aria-label="Previous">
                                    <span class="fa fa-angle-double-left" aria-hidden="true"></span>
                                    <span class="sr-only">Previous</span>
                                  </a>
                                </li>
                                <li class="page-item active"><a class="page-link" href="#">1</a></li>
                                <li class="page-item"><a class="page-link" href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item">
                                  <a class="page-link" href="#" aria-label="Next">
                                    <span class="fa fa-angle-double-right" aria-hidden="true"></span>
                                    <span class="sr-only">Next</span>
                                  </a>
                                </li>
                              </ul>
                            </nav>
                        </div>
                    </div>
                </div>

                <div class="col-lg-4 pt-3 pt-lg-0">
                    <!-- Social Follow Start -->
                    <div class="pb-3">
                        <div class="bg-light py-2 px-4 mb-3">
                            <h3 class="m-0">Follow Us</h3>
                        </div>
                    {% for platform in platforms %}
                        {% if forloop.first or forloop.counter0|divisibleby:2 %}
                        <div class="d-flex mb-3">
                        {% endif %}

                            <a href="{{platform.platform_link}}" class="d-block w-50 py-2 px-3 text-white text-decoration-none {% if forloop.counter0|divisibleby:2 %} mr-2 {% else %} ml-2 {% endif %}" style="background: {{platform.bg_color}};">
                                <small class="{{platform.icons}} mr-2"></small><small>{{platform.followers}}</small>
                            </a>
                        {% if forloop.counter|divisibleby:2 or forloop.last %}
                        </div>
                        {% endif %}
                    {% endfor %}
                    </div>
                    <!-- Social Follow End -->

                    <!-- Newsletter Start -->
                    <div class="pb-3">
                        <div class="bg-light py-2 px-4 mb-3">
                            <h3 class="m-0">Newsletter</h3>
                        </div>
                        <div class="bg-light text-center p-4 mb-3">
                            <p>Please enter a valid email address</p>
                            <div class="input-group" style="width: 100%;">
                                <input type="text" class="form-control form-control-lg" placeholder="Your Email">
                                <div class="input-group-append">
                                    <button class="btn btn-primary">Sign Up</button>
                                </div>
                            </div>
                            <small>Make sure to enter a correct email to receive updates.</small>
                        </div>
                    </div>
                    <!-- Newsletter End -->

                    <!-- Ads Start -->
                    <div class="mb-3 pb-3">
                        <a href=""><img class="img-fluid" src="img/news-500x280-4.jpg" alt=""></a>
                    </div>
                    <!-- Ads End -->

                    <!-- Popular News Start -->
                    <div class="pb-3">
                        <div class="bg-light py-2 px-4 mb-3">
                            <h3 class="m-0">Tranding</h3>
                        </div>
                        {% for popular in populars %}
                        <div class="d-flex mb-3">
                            <img src="{{popular.image.url}}" style="width: 100px; height: 100px; object-fit: cover;">
                            <div class="w-100 d-flex flex-column justify-content-center bg-light px-3" style="height: 100px;">
                                <div class="mb-1" style="font-size: 13px;">
                                    <a href="">{{popular.category}}</a>
                                    <span class="px-1">/</span>
                                    <span>{{popular.published_at}}</span>
                                </div>
                                <a class="h6 m-0" href="{{popular.link}}">{{popular.title}}</a>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <!-- Popular News End -->

                    <!-- Tags Start -->
                    <div class="pb-3">
                        <div class="bg-light py-2 px-4 mb-3">
                            <h3 class="m-0">Tags</h3>
                        </div>
                        <div class="d-flex flex-wrap m-n1">
                            {% for tag in tags %}
                            <a href="{{tag.link}}" class="btn btn-sm btn-outline-secondary m-1">{{tag.name}}</a>
                            {% endfor %}
                        </div>
                    </div>
                    <!-- Tags End -->
                </div>
            </div>
        </div>
    </div>
    <!-- News With Sidebar End -->
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
    <div class="container-fluid py-3">
        <div class="container">
                <div class="col-md-7">
                    <div class="contact-form bg-light mb-3" style="padding: 30px;">
                        <div id="success"></div>
                        <form method="post" name="sentMessage" id="contactForm" novalidate="novalidate">
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="col-md-6">
                                    <div class="control-group">
                                        {% render_field login_form.username type="text" class="form-control p-4" id="name" placeholder="Enter the username" required="required" data-validation-required-message="Please enter your name"type="text" class="form-control p-4" id="name" placeholder="Your Name" required="required" data-validation-required-message="Please enter username" %}
                                        <p class="help-block text-danger"></p>
                                    </div>
                                </div>
                            </div>
                            <div class="control-group">
                                {% render_field login_form.password type="password" class="form-control p-4" id="subject" placeholder="Password" required="required" data-validation-required-message="Please enter password" %}
                                <p class="help-block text-danger"></p>
                            </div>
                                <button class="btn btn-primary font-weight-semi-bold px-4" style="height: 50px;" type="submit" id="sendMessageButton">Login</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/single_news.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
<!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="container">
            <nav class="breadcrumb bg-transparent m-0 p-0">
                <a class="breadcrumb-item" href="{% url 'newsroom:home' %}">Home</a>
                <a class="breadcrumb-item" href="{% url 'newsroom:categories' %}">Category</a>
                <span class="breadcrumb-item active">{{main_part.category}}</span>
            </nav>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- News With Sidebar Start -->
    <div class="container-fluid py-3">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <!-- News Detail Start -->
                    <div class="position-relative mb-3">
                        <img class="img-fluid w-100" src="{{main_part.main_image.url}}" style="object-fit: cover;">
                        <div class="overlay position-relative bg-light">
                            <div class="mb-3">
                                <a href="{% url 'newsroom:categories' %}">{{main_part.category}}</a>
                                <span class="px-1">/</span>
                                <span>{{main_part.published_at}}</span>
                                <p>{{main_part.content}}</p>
                            </div>
                            <div>
                            {% for news in my_news %}
                                <h4 class="mb-3">{{news.title}}</h4>
                                <img class="img-fluid w-50 {% if forloop.counter|divisibleby:2 %} float-left {% else %} float-right {% endif %} mr-4 mb-2" src="{{news.news_image.url}}">
                                <p>{{news.content}}</p>
                            {% endfor %}
                            </div>
                        </div>
                    </div>
                    <!-- News Detail End -->

                    <!-- Comment List Start -->
                    <div class="bg-light mb-3" style="padding: 30px;">
                        <h3 class="mb-4">{{ user_comments.count }} Comments</h3>
                        {% for comment in user_comments %}
                        <div class="media">
                            <img src="{{comment.image.url}}" alt="Image" class="img-fluid mr-3 mt-1" style="width: 45px;">
                            <div class="media-body">
                                <h6><a href="">{{comment.name}}</a> <small><i>{{comment.created_at}}</i></small></h6>
                                <p>{{comment.comment}}</p>
                                <button class="btn btn-sm btn-outline-secondary">Reply</button>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <!-- Comment List End -->

                    <!-- Comment Form Start -->
                    <div class="bg-light mb-3" style="padding: 30px;">
                        <h3 class="mb-4">Leave a comment</h3>
                        <form method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="name">Name *</label>
                                {% render_field form.name type="text" class="form-control" id="name" %}
                            </div>
                            <div class="form-group">
                                 <label for="email">Email *</label>
                                {% render_field form.email type="email" class="form-control" id="email" %}
                            </div>
                            <div class="form-group">
                                 <label for="website">Website *</label>
                                {% render_field form.website type="url" class="form-control" id="website" %}
                            </div>

                            <div class="form-group">
                                 <label for="message">Message *</label>
                                {% render_field form.message id="message" cols="30" rows="5" class="form-control" %}
                            </div>
                            <div class="form-group mb-0">
                                <input type="submit" value="Leave a comment"
                                    class="btn btn-primary font-weight-semi-bold py-2 px-3">
                            </div>
                        </form>
                    </div>
                    <!-- Comment Form End -->
                </div>

                <div class="col-lg-4 pt-3 pt-lg-0">
                    <!-- Social Follow Start -->
                    <div class="pb-3">
                        <div class="bg-light py-2 px-4 mb-3">
                            <h3 class="m-0">Follow Us</h3>
                        </div>
                    {% for platform in platforms %}
                        {% if forloop.first or forloop.counter0|divisibleby:2 %}
                        <div class="d-flex mb-3">
                        {% endif %}

                            <a href="{{platform.platform_link}}" class="d-block w-50 py-2 px-3 text-white text-decoration-none {% if forloop.counter0|divisibleby:2 %} mr-2 {% else %} ml-2 {% endif %}" style="background: {{platform.bg_color}};">
                                <small class="{{platform.icons}} mr-2"></small><small>{{platform.followers}}</small>
                            </a>
                        {% if forloop.counter|divisibleby:2 or forloop.last %}
                        </div>
                        {% endif %}
                    {% endfor %}
                    </div>
                    <!-- Social Follow End -->

                    <!-- Newsletter Start -->
                    <div class="pb-3">
                        <div class="bg-light py-2 px-4 mb-3">
                            <h3 class="m-0">Newsletter</h3>
                        </div>
                        <div class="bg-light text-center p-4 mb-3">
                            <p>Please enter a valid email address</p>
                            <div class="input-group" style="width: 100%;">
                                <input type="text" class="form-control form-control-lg" placeholder="Your Email">
                                <div class="input-group-append">
                                    <button class="btn btn-primary">Sign Up</button>
                                </div>
                            </div>
                            <small>Make sure to enter a correct email to receive updates.</small>
                        </div>
                    </div>
                    <!-- Newsletter End -->

                    <!-- Ads Start -->
                    <div class="mb-3 pb-3">
                        <a href=""><img class="img-fluid" src="img/news-500x280-4.jpg" alt=""></a>
                    </div>
                    <!-- Ads End -->

                    <!-- Popular News Start -->
                    <div class="pb-3">
                        <div class="bg-light py-2 px-4 mb-3">
                            <h3 class="m-0">Tranding</h3>
                        </div>
                        {% for popular in populars %}
                        <div class="d-flex mb-3">
                            <img src="{{popular.image.url}}" style="width: 100px; height: 100px; object-fit: cover;">
                            <div class="w-100 d-flex flex-column justify-content-center bg-light px-3" style="height: 100px;">
                                <div class="mb-1" style="font-size: 13px;">
                                    <a href="">{{popular.category}}</a>
                                    <span class="px-1">/</span>
                                    <span>{{popular.published_at}}</span>
                                </div>
                                <a class="h6 m-0" href="{{popular.link}}">{{popular.title}}</a>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <!-- Popular News End -->

                    <!-- Tags Start -->
                    <div class="pb-3">
                        <div class="bg-light py-2 px-4 mb-3">
                            <h3 class="m-0">Tags</h3>
                        </div>
                        <div class="d-flex flex-wrap m-n1">
                            {% for tag in tags %}
                            <a href="{{tag.link}}" class="btn btn-sm btn-outline-secondary m-1">{{tag.name}}</a>
                            {% endfor %}
                        </div>
                    </div>
                    <!-- Tags End -->
                </div>
            </div>
        </div>
    </div>
    </div>
    <!-- News With Sidebar End -->
{% endblock %}